version: '3.8'

services:
  app:
    image: ghcr.io/luxora-agency/luxoinbox:develop
    expose:
      - "3000"
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_TO_STDOUT=enabled
      - RAILS_SERVE_STATIC_FILES=1
      - PORT=3000
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    restart: unless-stopped
