export default {
  id: 'bulk-actions',
  category: 'conversations',
  icon: 'i-lucide-list-checks',
  order: 240,
  audience: 'all',
  featureFlag: null,
  // Verbatim from the `home` route meta.
  permissions: [
    'administrator',
    'agent',
    'conversation_manage',
    'conversation_unassigned_manage',
    'conversation_participating_manage',
  ],
  estimatedMinutes: 4,
  route: { name: 'home' },
  pageRoutes: ['home'],
  keywords: [
    'acciones masivas',
    'seleccion multiple',
    'selección múltiple',
    'lote',
    'bulk',
    'asignar varias',
  ],
  mobileSafe: false,
  steps: [
    {
      target: '[data-tour="conversation-list"]',
      i18nKey: 'BULK_ACTIONS.WHERE',
      side: 'right',
      align: 'start',
    },
    {
      target: '[data-tour="conversation-card-select"]',
      i18nKey: 'BULK_ACTIONS.SELECT',
      side: 'right',
      align: 'start',
      requiresConversation: true,
    },
    {
      // Selecting is a toggle, so every step that needs the bar open selects
      // the first card on entry and deselects it on the way out.
      target: '[data-tour="conversation-bulk-actions"]',
      i18nKey: 'BULK_ACTIONS.BAR',
      side: 'top',
      align: 'center',
      requiresConversation: true,
      before: { click: '[data-tour="conversation-card-select"]' },
      after: { click: '[data-tour="conversation-card-select"]' },
    },
    {
      target: '[data-tour="conversation-bulk-agent"]',
      i18nKey: 'BULK_ACTIONS.AGENT',
      side: 'top',
      align: 'center',
      requiresConversation: true,
      before: { click: '[data-tour="conversation-card-select"]' },
      after: { click: '[data-tour="conversation-card-select"]' },
    },
    {
      target: '[data-tour="conversation-bulk-team"]',
      i18nKey: 'BULK_ACTIONS.TEAM',
      side: 'top',
      align: 'center',
      requiresConversation: true,
      before: { click: '[data-tour="conversation-card-select"]' },
      after: { click: '[data-tour="conversation-card-select"]' },
    },
    {
      target: '[data-tour="conversation-bulk-label"]',
      i18nKey: 'BULK_ACTIONS.LABEL',
      side: 'top',
      align: 'center',
      requiresConversation: true,
      before: { click: '[data-tour="conversation-card-select"]' },
      after: { click: '[data-tour="conversation-card-select"]' },
    },
    {
      target: '[data-tour="conversation-bulk-update"]',
      i18nKey: 'BULK_ACTIONS.STATUS',
      side: 'top',
      align: 'center',
      requiresConversation: true,
      before: { click: '[data-tour="conversation-card-select"]' },
      after: { click: '[data-tour="conversation-card-select"]' },
    },
    {
      target: '[data-tour="conversation-bulk-select-all"]',
      i18nKey: 'BULK_ACTIONS.SELECT_ALL',
      side: 'top',
      align: 'start',
      requiresConversation: true,
      before: { click: '[data-tour="conversation-card-select"]' },
      after: { click: '[data-tour="conversation-card-select"]' },
    },
    {
      target: null,
      i18nKey: 'BULK_ACTIONS.SCOPE',
    },
    {
      target: null,
      i18nKey: 'BULK_ACTIONS.FINISH',
    },
  ],
};
