import { FEATURE_FLAGS } from 'dashboard/featureFlags';

export default {
  id: 'composer-advanced',
  category: 'conversations',
  icon: 'i-lucide-pen-line',
  order: 270,
  audience: 'all',
  featureFlag: null,
  // Verbatim from the `home` / `inbox_conversation` route meta.
  permissions: [
    'administrator',
    'agent',
    'conversation_manage',
    'conversation_unassigned_manage',
    'conversation_participating_manage',
  ],
  estimatedMinutes: 5,
  route: { name: 'home' },
  pageRoutes: ['home', 'inbox_conversation'],
  keywords: [
    'editor',
    'adjuntos',
    'emoji',
    'audio',
    'firma',
    'plantillas',
    'variables',
    'menciones',
    'composer',
  ],
  conversationScoped: true,
  mobileSafe: false,
  steps: [
    {
      target: '[data-tour="composer-actions"]',
      i18nKey: 'COMPOSER_ADVANCED.TOOLBAR',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="composer-emoji"]',
      i18nKey: 'COMPOSER_ADVANCED.EMOJI',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      // The file input itself is a 1px off-screen control; the visible target
      // is the wrapper the upload component renders around the paperclip.
      target: '[data-tour="composer-actions"] .file-uploads',
      i18nKey: 'COMPOSER_ADVANCED.ATTACHMENTS',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="composer-audio"]',
      i18nKey: 'COMPOSER_ADVANCED.AUDIO',
      side: 'top',
      align: 'start',
      requiresConversation: true,
      featureFlag: FEATURE_FLAGS.VOICE_RECORDER,
    },
    {
      target: '[data-tour="composer-signature"]',
      i18nKey: 'COMPOSER_ADVANCED.SIGNATURE',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="composer-quote"]',
      i18nKey: 'COMPOSER_ADVANCED.QUOTE',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="composer-wa-template"]',
      i18nKey: 'COMPOSER_ADVANCED.WA_TEMPLATE',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="composer-article"]',
      i18nKey: 'COMPOSER_ADVANCED.ARTICLE',
      side: 'top',
      align: 'start',
      requiresConversation: true,
      featureFlag: FEATURE_FLAGS.HELP_CENTER,
    },
    {
      target: '[data-tour="composer-editor"]',
      i18nKey: 'COMPOSER_ADVANCED.SHORTCUTS',
      side: 'top',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="composer-send"]',
      i18nKey: 'COMPOSER_ADVANCED.SEND',
      side: 'top',
      align: 'end',
      requiresConversation: true,
    },
  ],
};
