export default {
  id: 'contact-panel',
  category: 'conversations',
  icon: 'i-lucide-panel-right',
  order: 260,
  audience: 'all',
  featureFlag: null,
  // Verbatim from the `home` / `inbox_conversation` route meta.
  permissions: [
    'administrator',
    'agent',
    'conversation_manage',
    'conversation_unassigned_manage',
    'conversation_participating_manage',
  ],
  estimatedMinutes: 4,
  route: { name: 'home' },
  pageRoutes: ['home', 'inbox_conversation'],
  keywords: [
    'panel',
    'contacto',
    'atributos',
    'notas',
    'participantes',
    'adjuntos',
    'conversaciones anteriores',
  ],
  conversationScoped: true,
  mobileSafe: false,
  steps: [
    {
      target: '[data-tour="conversation-sidebar"]',
      i18nKey: 'CONTACT_PANEL.PANEL',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="sidepanel-switch"]',
      i18nKey: 'CONTACT_PANEL.SWITCH',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-info"]',
      i18nKey: 'CONTACT_PANEL.INFO',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-actions"]',
      i18nKey: 'CONTACT_PANEL.ACTIONS',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-participants"]',
      i18nKey: 'CONTACT_PANEL.PARTICIPANTS',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-conversation-info"]',
      i18nKey: 'CONTACT_PANEL.CONVERSATION_INFO',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-attributes"]',
      i18nKey: 'CONTACT_PANEL.ATTRIBUTES',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-previous-conversations"]',
      i18nKey: 'CONTACT_PANEL.PREVIOUS',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-notes"]',
      i18nKey: 'CONTACT_PANEL.NOTES',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
    {
      target: '[data-tour="contact-panel-shared-files"]',
      i18nKey: 'CONTACT_PANEL.FILES',
      side: 'left',
      align: 'start',
      requiresConversation: true,
    },
  ],
};
