export default {
  id: 'conversation-views',
  category: 'conversations',
  icon: 'i-lucide-folder-tree',
  order: 220,
  audience: 'all',
  featureFlag: null,
  // Verbatim from the `home` route meta, shared by every conversation route.
  permissions: [
    'administrator',
    'agent',
    'conversation_manage',
    'conversation_unassigned_manage',
    'conversation_participating_manage',
  ],
  estimatedMinutes: 4,
  route: { name: 'home' },
  pageRoutes: [
    'home',
    'conversation_mentions',
    'conversation_participating',
    'conversation_unattended',
  ],
  keywords: [
    'vistas',
    'menciones',
    'desatendido',
    'carpetas',
    'equipos',
    'canales',
    'etiquetas',
    'views',
  ],
  mobileSafe: false,
  steps: [
    {
      target: '[data-tour="sidebar-conversation"]',
      i18nKey: 'CONVERSATION_VIEWS.GROUP',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-conversation-all"]',
      i18nKey: 'CONVERSATION_VIEWS.ALL',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-conversation-mentions"]',
      i18nKey: 'CONVERSATION_VIEWS.MENTIONS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-conversation-participating"]',
      i18nKey: 'CONVERSATION_VIEWS.PARTICIPATING',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-conversation-unattended"]',
      i18nKey: 'CONVERSATION_VIEWS.UNATTENDED',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-subgroup-folders"]',
      i18nKey: 'CONVERSATION_VIEWS.FOLDERS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-subgroup-teams"]',
      i18nKey: 'CONVERSATION_VIEWS.TEAMS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-subgroup-channels"]',
      i18nKey: 'CONVERSATION_VIEWS.CHANNELS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-subgroup-labels"]',
      i18nKey: 'CONVERSATION_VIEWS.LABELS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: null,
      i18nKey: 'CONVERSATION_VIEWS.FINISH',
    },
  ],
};
