import { FEATURE_FLAGS } from 'dashboard/featureFlags';

export default {
  id: 'navigation',
  category: 'start',
  icon: 'i-lucide-panel-left',
  order: 110,
  audience: 'all',
  featureFlag: null,
  // Verbatim from the `home` route meta.
  permissions: [
    'administrator',
    'agent',
    'conversation_manage',
    'conversation_unassigned_manage',
    'conversation_participating_manage',
  ],
  estimatedMinutes: 4,
  route: { name: 'home' },
  pageRoutes: ['home'],
  keywords: [
    'menu',
    'menú',
    'barra lateral',
    'sidebar',
    'navegacion',
    'navegación',
    'navigation',
  ],
  mobileSafe: false,
  steps: [
    {
      target: '[data-tour="sidebar-inbox"]',
      i18nKey: 'NAVIGATION.INBOX',
      side: 'right',
      align: 'start',
    },
    {
      target: '[data-tour="sidebar-conversation"]',
      i18nKey: 'NAVIGATION.CONVERSATIONS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-subgroup-channels"]',
      i18nKey: 'NAVIGATION.SUBGROUPS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Conversation' },
    },
    {
      target: '[data-tour="sidebar-contacts"]',
      i18nKey: 'NAVIGATION.CONTACTS',
      side: 'right',
      align: 'start',
      featureFlag: FEATURE_FLAGS.CRM,
      permissions: ['administrator', 'agent', 'contact_manage'],
    },
    {
      target: '[data-tour="sidebar-reports"]',
      i18nKey: 'NAVIGATION.REPORTS',
      side: 'right',
      align: 'start',
      featureFlag: FEATURE_FLAGS.REPORTS,
      permissions: ['administrator', 'report_manage'],
    },
    {
      target: '[data-tour="sidebar-settings"]',
      i18nKey: 'NAVIGATION.SETTINGS',
      side: 'right',
      align: 'start',
      before: { expandSidebarGroup: 'Settings' },
    },
    {
      target: '[data-tour="sidebar-settings-account-settings"]',
      i18nKey: 'NAVIGATION.SETTINGS_SECTIONS',
      side: 'right',
      align: 'start',
      permissions: ['administrator'],
      before: { expandSidebarGroup: 'Settings' },
    },
    {
      target: '[data-tour="sidebar-search"]',
      i18nKey: 'NAVIGATION.SEARCH',
      side: 'right',
      align: 'start',
    },
    {
      target: '[data-tour="sidebar-compose"]',
      i18nKey: 'NAVIGATION.COMPOSE',
      side: 'right',
      align: 'start',
    },
    {
      target: '[data-tour="sidebar-collapse-toggle"]',
      i18nKey: 'NAVIGATION.COLLAPSE',
      side: 'right',
      align: 'end',
    },
  ],
};
